API:
    PORT: '3000'
    LOG:
        LEVEL: 'verbose'
    CLIENT:
        SECRET: 'the_development_client_session_secret'

SERVICES:
    DATABASE:
        URL: 'postgresql://postgres:postgres@127.0.0.1:5432/open_market?pool_timeout=30&connect_timeout=30'
