API:
    PORT: '9099'

LOG:
    LEVEL: 'debug'

DATABASE:
    URL: 'postgresql://postgres:postgres@127.0.0.1:5432/myopenmarket?pool_timeout=30&connect_timeout=30'

CLIENT_SESSION:
    SECRET: 'the_test_client_session_secret'