name: CI Build Pipeline
on:
  push:
    branches:
      - main
      - develop
jobs:
  test:
    name: Run project tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v2

      - name: Run tests with docker
        run: yarn docker:test
