name: Build Pipeline
on:
  push:
    branches:
      - main
      - develop
jobs:
  test:
    name: Test API
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v2

      - name: Run tests with docker
        run: sh scripts/docker-test.sh
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
